// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Fork extends pulumi.CustomResource {
    /**
     * Get an existing Fork resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ForkState, opts?: pulumi.CustomResourceOptions): Fork {
        return new Fork(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'gitea:index/fork:Fork';

    /**
     * Returns true if the given object is an instance of Fork.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Fork {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Fork.__pulumiType;
    }

    public readonly forkId!: pulumi.Output<string>;
    /**
     * The organization that owns the forked repo
     */
    public readonly organization!: pulumi.Output<string | undefined>;
    /**
     * The owner or owning organization of the repository to fork
     */
    public readonly owner!: pulumi.Output<string>;
    /**
     * The name of the repository to fork
     */
    public readonly repo!: pulumi.Output<string>;

    /**
     * Create a Fork resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ForkArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ForkArgs | ForkState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ForkState | undefined;
            resourceInputs["forkId"] = state ? state.forkId : undefined;
            resourceInputs["organization"] = state ? state.organization : undefined;
            resourceInputs["owner"] = state ? state.owner : undefined;
            resourceInputs["repo"] = state ? state.repo : undefined;
        } else {
            const args = argsOrState as ForkArgs | undefined;
            if ((!args || args.owner === undefined) && !opts.urn) {
                throw new Error("Missing required property 'owner'");
            }
            if ((!args || args.repo === undefined) && !opts.urn) {
                throw new Error("Missing required property 'repo'");
            }
            resourceInputs["forkId"] = args ? args.forkId : undefined;
            resourceInputs["organization"] = args ? args.organization : undefined;
            resourceInputs["owner"] = args ? args.owner : undefined;
            resourceInputs["repo"] = args ? args.repo : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Fork.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Fork resources.
 */
export interface ForkState {
    forkId?: pulumi.Input<string>;
    /**
     * The organization that owns the forked repo
     */
    organization?: pulumi.Input<string>;
    /**
     * The owner or owning organization of the repository to fork
     */
    owner?: pulumi.Input<string>;
    /**
     * The name of the repository to fork
     */
    repo?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Fork resource.
 */
export interface ForkArgs {
    forkId?: pulumi.Input<string>;
    /**
     * The organization that owns the forked repo
     */
    organization?: pulumi.Input<string>;
    /**
     * The owner or owning organization of the repository to fork
     */
    owner: pulumi.Input<string>;
    /**
     * The name of the repository to fork
     */
    repo: pulumi.Input<string>;
}
