// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getRepo(args: GetRepoArgs, opts?: pulumi.InvokeOptions): Promise<GetRepoResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitea:index/getRepo:getRepo", {
        "id": args.id,
        "name": args.name,
        "username": args.username,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepo.
 */
export interface GetRepoArgs {
    id?: string;
    name: string;
    username: string;
}

/**
 * A collection of values returned by getRepo.
 */
export interface GetRepoResult {
    readonly cloneUrl: string;
    readonly created: string;
    readonly defaultBranch: string;
    readonly description: string;
    readonly fork: boolean;
    readonly forks: number;
    readonly fullName: string;
    readonly htmlUrl: string;
    readonly id: string;
    readonly mirror: boolean;
    readonly name: string;
    readonly openIssueCount: number;
    readonly permissionAdmin: boolean;
    readonly permissionPull: boolean;
    readonly permissionPush: boolean;
    readonly private: boolean;
    readonly size: number;
    readonly sshUrl: string;
    readonly stars: number;
    readonly updated: string;
    readonly username: string;
    readonly watchers: number;
    readonly website: string;
}
export function getRepoOutput(args: GetRepoOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepoResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gitea:index/getRepo:getRepo", {
        "id": args.id,
        "name": args.name,
        "username": args.username,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepo.
 */
export interface GetRepoOutputArgs {
    id?: pulumi.Input<string>;
    name: pulumi.Input<string>;
    username: pulumi.Input<string>;
}
