// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class GitHook extends pulumi.CustomResource {
    /**
     * Get an existing GitHook resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GitHookState, opts?: pulumi.CustomResourceOptions): GitHook {
        return new GitHook(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'gitea:index/gitHook:GitHook';

    /**
     * Returns true if the given object is an instance of GitHook.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GitHook {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GitHook.__pulumiType;
    }

    /**
     * Content of the git hook
     */
    public readonly content!: pulumi.Output<string>;
    public readonly gitHookId!: pulumi.Output<string>;
    /**
     * Name of the git hook to configure
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The repository that this hook belongs too.
     */
    public readonly repo!: pulumi.Output<string>;
    /**
     * The user (or organisation) owning the repo this hook belongs too
     */
    public readonly user!: pulumi.Output<string>;

    /**
     * Create a GitHook resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GitHookArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GitHookArgs | GitHookState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GitHookState | undefined;
            resourceInputs["content"] = state ? state.content : undefined;
            resourceInputs["gitHookId"] = state ? state.gitHookId : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["repo"] = state ? state.repo : undefined;
            resourceInputs["user"] = state ? state.user : undefined;
        } else {
            const args = argsOrState as GitHookArgs | undefined;
            if ((!args || args.content === undefined) && !opts.urn) {
                throw new Error("Missing required property 'content'");
            }
            if ((!args || args.repo === undefined) && !opts.urn) {
                throw new Error("Missing required property 'repo'");
            }
            if ((!args || args.user === undefined) && !opts.urn) {
                throw new Error("Missing required property 'user'");
            }
            resourceInputs["content"] = args ? args.content : undefined;
            resourceInputs["gitHookId"] = args ? args.gitHookId : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["repo"] = args ? args.repo : undefined;
            resourceInputs["user"] = args ? args.user : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(GitHook.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering GitHook resources.
 */
export interface GitHookState {
    /**
     * Content of the git hook
     */
    content?: pulumi.Input<string>;
    gitHookId?: pulumi.Input<string>;
    /**
     * Name of the git hook to configure
     */
    name?: pulumi.Input<string>;
    /**
     * The repository that this hook belongs too.
     */
    repo?: pulumi.Input<string>;
    /**
     * The user (or organisation) owning the repo this hook belongs too
     */
    user?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a GitHook resource.
 */
export interface GitHookArgs {
    /**
     * Content of the git hook
     */
    content: pulumi.Input<string>;
    gitHookId?: pulumi.Input<string>;
    /**
     * Name of the git hook to configure
     */
    name?: pulumi.Input<string>;
    /**
     * The repository that this hook belongs too.
     */
    repo: pulumi.Input<string>;
    /**
     * The user (or organisation) owning the repo this hook belongs too
     */
    user: pulumi.Input<string>;
}
