// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class GpgKey extends pulumi.CustomResource {
    /**
     * Get an existing GpgKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GpgKeyState, opts?: pulumi.CustomResourceOptions): GpgKey {
        return new GpgKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'gitea:index/gpgKey:GpgKey';

    /**
     * Returns true if the given object is an instance of GpgKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GpgKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GpgKey.__pulumiType;
    }

    /**
     * An armored GPG public key
     */
    public readonly armoredPublicKey!: pulumi.Output<string>;
    public readonly gpgKeyId!: pulumi.Output<string>;
    /**
     * The ID of the GPG key
     */
    public /*out*/ readonly keyId!: pulumi.Output<string>;

    /**
     * Create a GpgKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GpgKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GpgKeyArgs | GpgKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GpgKeyState | undefined;
            resourceInputs["armoredPublicKey"] = state ? state.armoredPublicKey : undefined;
            resourceInputs["gpgKeyId"] = state ? state.gpgKeyId : undefined;
            resourceInputs["keyId"] = state ? state.keyId : undefined;
        } else {
            const args = argsOrState as GpgKeyArgs | undefined;
            if ((!args || args.armoredPublicKey === undefined) && !opts.urn) {
                throw new Error("Missing required property 'armoredPublicKey'");
            }
            resourceInputs["armoredPublicKey"] = args ? args.armoredPublicKey : undefined;
            resourceInputs["gpgKeyId"] = args ? args.gpgKeyId : undefined;
            resourceInputs["keyId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(GpgKey.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering GpgKey resources.
 */
export interface GpgKeyState {
    /**
     * An armored GPG public key
     */
    armoredPublicKey?: pulumi.Input<string>;
    gpgKeyId?: pulumi.Input<string>;
    /**
     * The ID of the GPG key
     */
    keyId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a GpgKey resource.
 */
export interface GpgKeyArgs {
    /**
     * An armored GPG public key
     */
    armoredPublicKey: pulumi.Input<string>;
    gpgKeyId?: pulumi.Input<string>;
}
