// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class PublicKey extends pulumi.CustomResource {
    /**
     * Get an existing PublicKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PublicKeyState, opts?: pulumi.CustomResourceOptions): PublicKey {
        return new PublicKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'gitea:index/publicKey:PublicKey';

    /**
     * Returns true if the given object is an instance of PublicKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PublicKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PublicKey.__pulumiType;
    }

    public /*out*/ readonly created!: pulumi.Output<string>;
    public /*out*/ readonly fingerprint!: pulumi.Output<string>;
    /**
     * An armored SSH key to add
     */
    public readonly key!: pulumi.Output<string>;
    public readonly publicKeyId!: pulumi.Output<string>;
    /**
     * Describe if the key has only read access or read/write
     */
    public readonly readOnly!: pulumi.Output<boolean | undefined>;
    /**
     * Title of the key to add
     */
    public readonly title!: pulumi.Output<string>;
    public /*out*/ readonly type!: pulumi.Output<string>;
    /**
     * User to associate with the added key
     */
    public readonly username!: pulumi.Output<string>;

    /**
     * Create a PublicKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PublicKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PublicKeyArgs | PublicKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PublicKeyState | undefined;
            resourceInputs["created"] = state ? state.created : undefined;
            resourceInputs["fingerprint"] = state ? state.fingerprint : undefined;
            resourceInputs["key"] = state ? state.key : undefined;
            resourceInputs["publicKeyId"] = state ? state.publicKeyId : undefined;
            resourceInputs["readOnly"] = state ? state.readOnly : undefined;
            resourceInputs["title"] = state ? state.title : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
            resourceInputs["username"] = state ? state.username : undefined;
        } else {
            const args = argsOrState as PublicKeyArgs | undefined;
            if ((!args || args.key === undefined) && !opts.urn) {
                throw new Error("Missing required property 'key'");
            }
            if ((!args || args.title === undefined) && !opts.urn) {
                throw new Error("Missing required property 'title'");
            }
            if ((!args || args.username === undefined) && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["key"] = args?.key ? pulumi.secret(args.key) : undefined;
            resourceInputs["publicKeyId"] = args ? args.publicKeyId : undefined;
            resourceInputs["readOnly"] = args ? args.readOnly : undefined;
            resourceInputs["title"] = args ? args.title : undefined;
            resourceInputs["username"] = args ? args.username : undefined;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["fingerprint"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["key"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(PublicKey.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering PublicKey resources.
 */
export interface PublicKeyState {
    created?: pulumi.Input<string>;
    fingerprint?: pulumi.Input<string>;
    /**
     * An armored SSH key to add
     */
    key?: pulumi.Input<string>;
    publicKeyId?: pulumi.Input<string>;
    /**
     * Describe if the key has only read access or read/write
     */
    readOnly?: pulumi.Input<boolean>;
    /**
     * Title of the key to add
     */
    title?: pulumi.Input<string>;
    type?: pulumi.Input<string>;
    /**
     * User to associate with the added key
     */
    username?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a PublicKey resource.
 */
export interface PublicKeyArgs {
    /**
     * An armored SSH key to add
     */
    key: pulumi.Input<string>;
    publicKeyId?: pulumi.Input<string>;
    /**
     * Describe if the key has only read access or read/write
     */
    readOnly?: pulumi.Input<boolean>;
    /**
     * Title of the key to add
     */
    title: pulumi.Input<string>;
    /**
     * User to associate with the added key
     */
    username: pulumi.Input<string>;
}
