// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getBot(args?: GetBotArgs, opts?: pulumi.InvokeOptions): Promise<GetBotResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("telegram:index/getBot:getBot", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getBot.
 */
export interface GetBotArgs {
    id?: string;
}

/**
 * A collection of values returned by getBot.
 */
export interface GetBotResult {
    readonly id: string;
    readonly name: string;
    readonly userId: number;
    readonly username: string;
}
export function getBotOutput(args?: GetBotOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetBotResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("telegram:index/getBot:getBot", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getBot.
 */
export interface GetBotOutputArgs {
    id?: pulumi.Input<string>;
}
