;; -*- no-byte-compile: t; -*-
;;; private/exwm/packages.el

(package! dmenu)
(package! circadian)
(package! spotify)
(package! pulseaudio-control)
;; (package! gpastel)
(package! xelb)
(package! exwm)
(package! color-theme-sanityinc-tomorrow)
(package! anti-zenburn-theme)
(package! kaolin-themes)
(package! nord-theme)
(package! frame-purpose)
(package! frame-workflow :recipe (:host github :repo "akirak/frame-workflow"))
(package! counsel-spotify)
(package! emms)
(package! backlight)
;; (package! exwm-mff :recipe (:host github :repo "ieure/exwm-mff"))
