lock := "0"
guix-lock := if lock != "0" { "guix time-machine -C channels.lock --" } else { "guix" }

default:
    @just --list

l *args:
    @just -f {{source_file()}} {{args}} -L ~/devel/dotfiles/guix/personal

refresh *args='':
    guix refresh {{args}}

shell *args='':
    guix shell {{args}}

build *args='':
    guix build {{args}}

pull *args='':
    guix pull {{args}}

update-channels:
    guix describe --format=channels > channels.lock

system *args='':
    direnv exec . sudo -E {{ guix-lock }} system reconfigure system.scm {{args}}

home *args='':
    {{ guix-lock }} home reconfigure home.scm {{args}}

gc:
    guix home delete-generations
    sudo guix system delete-generations
    guix pull --delete-generations
    guix gc
