;; -*- no-byte-compile: t; -*-
;;; private/sarg/packages.el

(package! ox-hugo)
(package! puppet-mode)
(package! nginx-mode)
(package! multitran)
(package! slack)
(package! webpaste)
(package! dired-filter)
(package! dired-avfs)
(package! dired-du)
(package! dired-collapse)
;; (package! aria2
  ;; :recipe (:host gitlab :repo "ukaszg/aria2" :branch "remake"))
(package! openwith)
(package! web-search)
(package! keyfreq)
(package! dictcc)
(package! goldendict)
(package! mpv)
(package! el-patch)
(package! linkmarks :recipe (:host github :repo "dustinlacewell/linkmarks"))
(package! bencode :recipe (:host github :repo "skeeto/emacs-bencode"))
(package! sauron)
(package! google-translate)
(package! white-sand-theme)
;; (package! ranger)

(package! magit-todos :disable t)
