BROWSER=qutebrowser
PATH=$HOME/.local/bin:$PATH
PATH=$HOME/go/bin:$PATH
ALTERNATE_EDITOR=''
EDITOR='emacsclient'
PAGER=less
VISUAL=$EDITOR
PASSWORD_STORE_DIR=$HOME/Sync/pass

export EDITOR
export VISUAL
export BROWSER
export PATH
export ALTERNATE_EDITOR
export EDITOR
export VISUAL
export PASSWORD_STORE_DIR
